### ISSUE TITLE
sql: unknown Storage type - running latest release

### ISSUE THREAD

**Issue by hrn4n** [sourcegraph/checkup#67] opened 2017-09-13 17:00 UTC
I assume compiling from source fixes this. Would be nice if you could release a compiled binary that includes it :+1:

**Comment by titpetric** [comment] 2020-05-28 14:07
Correct, building from source is currently the only way to get a release. Closing as the issue isn't actionable, but we'll improve this in the future.

**Closed by titpetric** 2020-05-28 14:07 UTC
