### ISSUE TITLE
Can response with statusCode 2xx(whether it's 200 or 201) can both be regarded as  healthy status by httpchecker 

### ISSUE THREAD

**Issue by lightof410** [sourcegraph/checkup#92] opened 2019-01-17 12:43 UTC
now httpchecker only consider the statusCode 200 as healthy status by default or we can change other as healthy status by setting httpchecker.UpStatus. 
but I hope response with statusCode 2xx(whether it's 200 or 201) can both be regarded as  healthy status

**Comment by rrjanbiah** [comment] 2020-05-20 07:04
Possible duplicate of #112

**Closed** 2020-06-01 20:52 UTC
